site_name: RCCatUW
nav:
  - Home: index.md
  - 'Hyak':
    - About: hyak.md
    - 'Terms of Service': hyak_TOS.md
    - Prereqs: 'prerequisites.md'
    - 'Getting Access': hyak_access.md
  - 'Cloud': cloud.md
  - Events: https://calendar.washington.edu/sea_uwit-rc
  - People: people.md
  - Contact: contact.md
  - Governance: RCC_governance.md
#site_url: http://localhost/RCCatUW
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
  #palette:
  #  scheme: default
  #  primary: deep purple
  #  accent: amber

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/uw-rcc/shared_invite/zt-2l7ab48ar-S_SbfLiCsdpF~ofbCR0yIg
    - icon: fontawesome/solid/paper-plane
      link: mailto:hpcc@uw.edu
extra_css:
  - stylesheets/extra.css

markdown_extensions:
    - pymdownx.blocks.html
    - pymdownx.highlight

